FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# PolskieRadio - Sport

API Specification.

## Articles Collection [/articles]

### List All Articles [GET]

+ Response 200 (application/json)

        {
            "meta": 
            {
                "offset" : 0,
                "limit" : 2,
                "count" : 100
            }
            "data": 
                [
                    {
                        "id": 1,
                        "title": "Title 1",
                        "discipline": "FOOTBALL",
                        "thumbnail": {
                            "url": "http://sampleimage.com/image1.jpg,
                            "width": 200,
                            "height": 100
                        },
                        "hasVideo" : true,
                        "hasImage" : false
                    },
                    {
                        "id": 2,
                        "title": "Title 2",
                        "discipline": "VOLLEYBALL",
                        "thumbnail": {
                            "url": "http://sampleimage.com/image2.jpg,
                            "width": 200,
                            "height": 100
                        },
                        "hasVideo" : true,
                        "hasImage" : true
                    },
                ]
        }

+ Response 400 (application/json)

        {
            "errors":
            [
                {
                    "title": "invalid parameter",
                    "details": "parameter 'offfffset' is not a valid parameter",
                    "code": "1234"
                }
            ]
        }